elearn/urls.py
import django
from django.urls import path, include

from lms import settings
from . import views
from django.contrib.auth import views as auth_views

from django.contrib.auth import views as auth_views


urlpatterns = [

    # Shared URLs
    path('', views.home, name='home'),
    path('lsign/', views.LearnerSignUpView.as_view(), name='lsign'),
    path('login_form/', views.login_form, name='login_form'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('prof/', views.ProfView.as_view(), name='profcourses'),
    path('ent/', views.ENT.as_view(), name='entcourses'),
    path('demo/', views.Demo.as_view(), name='demo'),

    path('access', views.AccessList.as_view(), name='access'),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    # Admin URLs
    path('dashboard/', views.dashboard, name='dashboard'),
    path('course/', views.course, name='course'),
    path('post_course/', views.post_course, name='post_course'),
    path('aluser/', views.ListUserView.as_view(), name='aluser'),
    path('aduser/<int:pk>', views.ADeleteuser.as_view(), name='aduser'),
    path('acreate_profile/', views.acreate_profile, name='acreate_profile'),
    path('profile/', views.createprofile, name='profile'),

    path('auser_profile/', views.auser_profile, name='auser_profile'),
    path('acourse/', views.ListCourseView.as_view(), name='list_course'),
    path('dcourse/<int:pk>', views.ADeleteCourse.as_view(), name='dcourse'),
    path('acourse/<int:pk>', views.course_detail.as_view(), name='course_detail'),
    path('user/<int:pk>', views.user_detail.as_view(), name='user_detail'),

    path('update/<int:pk>', views.update_course, name='update_object'),
    path('update/updaterecord/<int:pk>', views.updaterecord, name='updaterecord'),
    path('add/<int:pk>', views.addcourse, name='addcourse'),
    path('updatet/<int:pk>', views.update_tutorial, name='update_tutorial'),
    path('updatet/updatetutor/<int:pk>', views.updatetutor, name='updatetutor'),
    path('addfile/<int:pk>', views.add_file, name='addfile'),
    path('addfile/addf/<int:pk>', views.addfile, name='addf'),
    path('tutorial/<int:pk>', views.tutorial, name='tutorial'),
    path('itutorials/<int:pk>/', views.ITutorialDetail.as_view(), name="itutorial-detail"),
    path('post/', views.publish_tutorial, name='publish_tutorial'),
    path('lesson/<int:pk>', views.module, name='itut'),
    path('usercourse/<int:pk>', views.usercourse, name='usercourse'),
    path('courseu/<int:pk>', views.courseu, name='courseu'),
    path('dusercourse/<int:pk>', views.dusercourse, name='dusercourse'),
    path('coursed/<int:pk>', views.coursed, name='coursed'),

    path('module/', views.module, name='module'),
    path('postmodule/', views.publish_module, name='publish-module'),

    # Instructor URLs
    path('quiz_add/<int:pk>', views.QuizCreateView.as_view(), name='quiz_add'),
    path('question_add/<int:pk>', views.question_add, name='question_add'),
    path('quiz/<int:quiz_pk>/<int:question_pk>/', views.question_change, name='question_change'),
    path('llist_quiz/', views.QuizListView.as_view(), name='quiz_change_list'),
    path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', views.QuestionDeleteView.as_view(),
         name='question_delete'),
    path('quiz/<int:pk>/results/', views.QuizResultsView.as_view(), name='quiz_results'),
    path('quiz/<int:pk>/delete/', views.QuizDeleteView.as_view(), name='quiz_delete'),
    path('quizupdate/<int:pk>/', views.QuizUpdateView.as_view(), name='quiz_change'),
    path('rating/<int:pk>', views.Rating.as_view(), name='rating'),

    # Learner URl's
    path('learner/', views.ShopView.as_view(), name='learner'),
    path('lcreate_profile/', views.lcreate_profile, name='lcreate_profile'),
    path('taken/<int:pk>', views.TakenQuizListView.as_view(), name='taken_quiz_list'),
    path('quiz/<int:pk>/', views.take_quiz, name='take_quiz'),
    path('shop/', views.ShopView.as_view(), name='shop'),
    path('courses/<int:pk>', views.scourse.as_view(), name='course'),
    path('buy/<int:pk>', views.buycourse, name='buy'),
    path('mycourses/', views.showmycourses, name='mycourses'),
    path('lessons/<int:pk>', views.Lesson.as_view(), name='lessons'),
    path('complete/<int:pk>', views.paymentComplete, name="complete"),
    path('test', views.model_form_view, name='test')

]

elearn/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.html import escape, mark_safe
from django.contrib.auth import get_user_model
from embed_video.fields import EmbedVideoField
import json
from decimal import Decimal

from django.test import TestCase
from tinymce.models import HTMLField


class User(AbstractUser):
    email = models.EmailField(max_length=254)
    is_learner = models.BooleanField(default=False)
    is_instructor = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='', default='no-img.jpg', blank=True)
    first_name = models.CharField(max_length=255, default='')
    last_name = models.CharField(max_length=255, default='', blank=True)
    email = models.EmailField(default='none@email.com')
    phonenumber = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, default='')
    state = models.CharField(max_length=255, default='')
    instagram = models.CharField(null=True, max_length=255, blank=True)
    TikTok = models.CharField(null=True, max_length=255, blank=True)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=30)
    cprice = models.IntegerField(null=True)
    synopsis = models.TextField(null=True, max_length=100)
    is_shown = models.BooleanField(default=False)
    thumb = models.ImageField(upload_to='', default='no-img.jpg', blank=True)
    students = models.ManyToManyField(User, default='')
    trainer = models.CharField(null=True, max_length=50, default='')
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.name


class Module(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.name


class Tutorial(models.Model):
    title = models.CharField(max_length=50)
    content = HTMLField()
    module = models.ForeignKey(Module, on_delete=models.CASCADE, default='', )
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = EmbedVideoField(blank=True, null=True)
    video2 = EmbedVideoField(blank=True, null=True)
    video3 = EmbedVideoField(blank=True, null=True)

    task = models.FileField(blank=True, null=True)

    def __str__(self):
        return self.title


class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quizzes')
    tutorial = models.ForeignKey(Tutorial, on_delete=models.CASCADE, related_name='quizzes', default='', null=False)
    reattempt = models.BooleanField(default=True, verbose_name='Allow Reattempt')

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField('Question', max_length=255)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Learner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Course, related_name='interested_learners')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class Access(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(null=True, auto_now_add=True)

    def __str__(self):
        return self.date


class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    interest = models.ManyToManyField(Course, related_name="more_locations")


class TakenQuiz(models.Model):
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.FloatField()
    correct = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)


class RatingModel(models.Model):
    learner = models.ForeignKey(Learner, on_delete=models.CASCADE, related_name='rating')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='rating')
    score = models.FloatField()
    correct = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)


class LearnerAnswer(models.Model):
    student = models.ForeignKey(Learner, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')

elearn/forms.py
from __future__ import unicode_literals

import hashlib
import json

from django.test import SimpleTestCase, TestCase

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from django import forms
from django.shortcuts import render

from elearn.models import (Answer, Question, Learner, LearnerAnswer,
                           Course, User, Profile, Tutorial)

import hashlib
import json
from base64 import b64encode

from django import forms


class ProfileForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput())
    confirm_email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('name', 'cprice', 'synopsis')


class UserForm(forms.ModelForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', required=True)

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email exists")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class InstructorSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def __init__(self, *args, **kwargs):
        super(InstructorSignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_instructor = True
        if commit:
            user.save()
        return user


class LearnerSignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.', required=True)

    class Meta(UserCreationForm.Meta):
        model = User

    def __init__(self, *args, **kwargs):
        super(LearnerSignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email', 'password1', 'password2', ]:
            self.fields[fieldname].help_text = None

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email exists")
        return self.cleaned_data

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_learner = True
        user.email = self.cleaned_data['email']
        user.save()
        Learner.objects.create(user=user)
        return user


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text',)


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = LearnerAnswer
        fields = ('answer',)

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Profile
        fields = ['avatar', 'phonenumber', 'state', 'city', 'first_name', 'last_name', 'TikTok', 'instagram']


class QuillPostForm(forms.ModelForm):
    class Meta:
        model = Tutorial
        fields = (
            'content',
        )

elearn/templates/dashboard/learner/_header.html
{% load i18n %}
<h2>Quizzes</h2>

<ul class="nav nav-tabs mb-3">

  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'taken_quiz_list' %}">{% trans 'Тесты' %}</a>
  </li>
</ul>

elearn/templates/dashboard/learner/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}Quantum Learning{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <script src="//cdn.tinymce.com/4/tinymce.js"></script>
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body class = "bg-light"style="background: url(); background-size: cover; ">
  <header class="pb-3">

<nav class="navbar navbar-expand-lg navbar-light border-bottom p-3 bg-white ">
  <div class="container-fluid">
       <a class="navbar-brand d-flex-inline" href="{% url 'learner' %}">
              <img src="{% static 'img/quantum.png' %}"  class = "logo"alt="">
          </a>
    <a class="navbar-brand" href="#"> <h5></h5></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        {% if user.is_learner %}
      <ul class="navbar-nav ms-auto ">
        <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'mycourses' %}">{% trans 'Мои курсы' %}</a>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Курсы
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="nav-link mx-2" aria-current="page" href="{% url 'profcourses' %}">{% trans 'Профессиональные курсы' %}</a></li>
            <li><a class="nav-link mx-2" href="{% url 'entcourses' %}">{% trans 'Курсы ЕНТ' %}</a></li>
            <li><a class="nav-link mx-2" href="{% url 'demo' %}">{% trans 'Демо курсы' %}</a></li>
          </ul>
        </li>
              <li class="nav-item">
            <a class="nav-link mx-2" href="">{% trans 'Новости' %}</a>
        </li>
              <li class="nav-item">
            <a class="nav-link mx-2" href="">{% trans 'Полезное' %}</a>
        </li>
      </ul>
      <ul class="navbar-nav navbar-expand-lg ms-auto  d-lg-inline-flex">
               <li class="nav-item dropdown">
          <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           {{ request.user.username }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href={% url 'auser_profile' %}>Аккаунт</a></li>
            <li><a class="dropdown-item" href={% url 'logout' %}>{% trans 'Выйти' %}</a></li>
            <li><a class="dropdown-item" href="#"></a></li>
          </ul>
        </li>
      </ul>
            {% else %}
                  <ul class="navbar-nav ms-auto d-none d-lg-inline-flex">
               <li class="nav-item dropdown">
          <a class="nav-link mx-2" href="{% url 'lsign' %}"  aria-expanded="false">
           Регистрация
          </a>
        </li>
      </ul>
        {% endif %}
    </div>
  </div>
</nav>

  </header>

  <main class="pt-5 pb-5">

    <div id="content">{% block body %} {% endblock %}</div>
  </main>

<footer class="text-center text-white bg-dark" style="background-color: #21081a;">
  <!-- Grid container -->
  <div class="container p-4"></div>
 <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            {% trans 'Контакты' %}
          </h6>
          <p><i class="fas fa-home me-3"></i> Quantum Group</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
                quantumgroup@gmail.com

          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright
  </div>
  <!-- Copyright -->
</footer>
</body>


</html>

elearn/templates/dashboard/learner/congrats.html
{% extends 'dashboard/learner/base.html' %}
{% load static %}
{% load i18n %}

{% block body %}
<div class="container" style = "width: 45%">
        <div class="card">
            <img src="{% static 'img/kaspi.png' %}" alt="">
         </div>



         </div>

</div>

{% endblock body %}

elearn/templates/dashboard/learner/course.html
{% extends 'dashboard/learner/base.html' %}
{% load i18n %}
{% load static %}
{% block body %}

    <section id="courses" class="py-4">
   <div class="container">
      <div class="row mb-5">
         <div class="col-md-9">
            <h1 class="display-6">{{ course.name }}</h1>
            <p class="text-justify">
               {{ course.synopsis }}
            </p>
         </div>
         <div class="col-md-3">
            <div class="card mb-3">
               {% if course.thumb %}
<div class="portfolio-img rounded overflow-hidden">
                      <img class="img-fluid" style = "width: 100%; height: 250px" src="{{ course.thumb.url}}" alt="">
</div>
               {% else %}
               <p>No image</p>
               {% endif %}
               <div class="card-body">
                  <h5 class="card-title">{% trans 'Автор курса' %}</h5>
                  <h6 class="text-secondary">{{ course.trainer }}</h6>
                  <hr>
                  <h6 class="text-secondary">{% trans 'Модули' %}: {{ course.module_set.count }}</h6>
                       {% if course not in user.course_set.all and course.category.slug != '3' %}
                  <div class="mb-3">
                            <a href="{% url 'buy' course.pk %}" class="btn btn-outline-info">{{course.cprice}}₸</a>
                            </div>
                           {% elif not user.is_learner %}
                           <a href="{% url 'lsign' %}" class="btn btn-outline-info">{% trans 'Купить' %}</a>

                   {% endif %}
               </div>
            </div>

         </div>
<div class="accordion accordion-flush" id="accordionFlushExample">
  {% for module in modules %}
      <div class="accordion-item">
         <h2 class="accordion-header" id="flush-heading-{{module.id}}">
             <ul>

                 <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#flush-collapse-{{module.id}}" aria-expanded="false" aria-
                controls="flush-collapse-{{module.id}}">
                <li>   {{module.name}}
                                      </li>
              </button>

             </ul>

         </h2>
 <div id="flush-collapse-{{module.id}}" class="accordion-collapse collapse" aria-
           labelledby="flush-heading-{{module.id}}" data-bs-parent="#accordionFlushExample">
             <div class="accordion-body">
                <ol type="1">
                    {% for tutorial in module.tutorial_set.all %}
                        {% if user.is_learner %}
                            <li><a href="{% url 'lessons' tutorial.pk %}">{{tutorial.title}} </a></li>
                            {% else %}
                            <li><a href="{% url 'lsign' %}">{{tutorial.title}} </a></li>

                        {% endif %}
                    {% endfor %}

                </ol>
             </div>

       </div>

</div>

{% endfor %}
   </div>
      </div>

   </div>
</section>

{% endblock %}

elearn/templates/dashboard/learner/home.html
{% extends 'dashboard/learner/base.html' %}
{% load i18n %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
{% block body %}
{% load static %}
        <!-- Google Web Fonts -->

<section>



                       <div class="container-xxl py-6 pt-5" id="project">
        <div class="container">
            <div class="row g-5 mb-5 align-items-center wow fadeInUp" data-wow-delay="0.1s">
                <div class="col-lg-6">
                    <h1 class="display-5 mb-0">{% trans 'Курсы' %}</h1>
                </div>

            </div>
                    <div class="row g-4 portfolio-container wow fadeInUp" data-wow-delay="0.1s">

                      {% if courses %}
        {% for course in courses %}
            {% if course.category.slug != '3' %}

                <div class="col-lg-4 col-md-6 portfolio-item first" style="width: 300px;">
                    <a href="{% url 'course' course.pk %}">
                        <div class="portfolio-img rounded overflow-hidden">
                      <img class="img-fluid" style = "width: 100%; height: 250px" src="{{ course.thumb.url}}" alt="">
                        <div class="portfolio-btn">
                            <h6 class = "text-white py-5 position-relative">{{ course.synopsis }}</h6>
=                            <p class = "text-white position-absolute">{% trans 'Цена' %}: {{ course.cprice }}₸</p>


                        </div>
                        </div>
                    </a>

                </div>
                        {% endif %}

                    {% endfor %}
                {% endif %}
                </div>
            </div>
</div>

</section>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>


    <!-- Template Javascript -->
    <script src="{% static 'mein.js/main.js' %}"></script>
{% endblock body %}

elearn/templates/dashboard/learner/rating.html
        {% extends 'dashboard/learner/base.html' %}
        {% load i18n %}

        {% load static %}
        {% load crispy_forms_tags humanize %}



        {% block body %}


        <div class="container">
          <h2 class="mb-3"> {% trans 'Результаты' %}</h2>

          <div class="sidebar">
                  <a href={% url 'course' object.course.pk %}><button class = bg-white>Вернуться к курсу</button></a>

            <table class="table">
              <thead>
                <tr>
                  <th>{% trans 'Имя пользователя' %}</th>
                  <th>{% trans 'Дата' %}</th>
                  <th>{% trans 'Баллы' %}</th>
                </tr>
              </thead>
              <tbody>
                {% for taken_quiz in taken_quizzes %}
                  <tr>
                        {% if taken_quiz.learner.user.profile %}
                            <td><a href="{% url 'user_detail' taken_quiz.learner.user.profile.pk %}">{{ taken_quiz.learner.user.username }}</a></td>
                        {% else %}
                            <td>{{  taken_quiz.learner.user.username  }}</td>

                        {% endif %}
                    <td>{{ taken_quiz.date|naturaltime  }}</td>
                    <td>{{ taken_quiz.score }}</td>

                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

        </div>
        <div class="container-fluid" style="padding-top: 20px">


            </div>

        {% endblock body %}